/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

var fibonacci;
fibonacci = (function() {
  var fib, memo;
  memo = [0, 1];
  return fib = function(n) {
    var _ref;
    return (_ref = memo[n]) != null ? _ref : memo[n] = fib(n - 1) + fib(n - 2);
  };
})();
console.log(fibonacci(34));
if (fibonacci(34) <= 4000000){ console.log("true")}
else{console.log("false")}
