
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


#include <stdio.h>
int main() {

    int sum =0;
    //printf("Output = %d", x & y);
    for (int i=0;i<4000000;i++){
        if(fib(i)%2==0){
            
            //printf( "%d\n", fib(i));
            if(fib(i)!=fib(i+1)){
                printf( "%d\n", fib(i));
                sum += fib(i);
            }
            
        }
        
    }
    
    if(fib(4000000-1)==fib(4000000)){
                printf( "%d\n", fib(4000000-1));
                sum += fib(4000000-1);
            }

    
    //int s=suma();
    printf("Output = %d", sum);

    return 0;
}

int fib(limit) {

    int a = 0, b = 1;
    while(a<limit) {
    int c = 0;
    c = a + b;
    a = b;
    b = c;
    if(b>limit){
        return a;
      }
    }
    //printf("Output = %d", a );
    
    //printf("Output = %d", a & b);

    return a;
}


